"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { normalizeCommercialUnit, presentationFactor, unitLabel, validBoxFactor } from "./commercial-units";

type Product={id:number;sku:string;name:string;unit:string;currentStock:number;boxFactor:number};
type Client={id:number;name:string};
type Data={products:Product[];clients:Client[];auth:{permissions:Record<string,boolean>}};

const labels:Record<string,string>={entrada_compra:"Entrada de mercancía",devolucion_cliente:"Devolución de cliente",devolucion_proveedor:"Devolución a proveedor",ajuste_positivo:"Ajuste positivo",ajuste_negativo:"Ajuste negativo"};
function buttonText(button:Element){return(button.textContent||"").replace(/\s+/g," ").trim()}

export default function CommercialMovementExperience(){
  const[open,setOpen]=useState(false),[data,setData]=useState<Data|null>(null),[productId,setProductId]=useState(""),[presentation,setPresentation]=useState("pieza"),[quantity,setQuantity]=useState("1"),[type,setType]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/data",{cache:"no-store"});const json=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(json.error||"No se pudo cargar la información.");setData(json);return json},[]);
  const options=useMemo(()=>{const p=data?.auth.permissions??{};const out:{value:string;label:string}[]=[];if(p["movements.purchase"])out.push({value:"entrada_compra",label:labels.entrada_compra});if(p["movements.returns"]){out.push({value:"devolucion_cliente",label:labels.devolucion_cliente});out.push({value:"devolucion_proveedor",label:labels.devolucion_proveedor})}if(p["movements.adjust"]){out.push({value:"ajuste_positivo",label:labels.ajuste_positivo});out.push({value:"ajuste_negativo",label:labels.ajuste_negativo})}return out},[data]);
  useEffect(()=>{function capture(event:MouseEvent){const target=event.target as HTMLElement|null;const button=target?.closest("button");if(!button||button.closest(".modal-backdrop"))return;const heading=document.querySelector(".content h1")?.textContent?.trim();if(heading!=="Movimientos")return;const label=buttonText(button);if(!label.includes("Registrar movimiento")&&!label.includes("Nuevo registro"))return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();void(async()=>{try{const json=await load();const product=json.products[0];setProductId(String(product?.id??""));setPresentation(normalizeCommercialUnit(product?.unit||"pieza"));const p=json.auth.permissions;const first=p["movements.purchase"]?"entrada_compra":p["movements.returns"]?"devolucion_cliente":p["movements.adjust"]?"ajuste_positivo":"";setType(first);setQuantity("1");setError("");setOpen(true)}catch(value){setError(value instanceof Error?value.message:"No se pudo abrir el movimiento.")}})()}document.addEventListener("click",capture,true);return()=>document.removeEventListener("click",capture,true)},[load]);
  const selected=data?.products.find(product=>String(product.id)===productId);const baseUnit=normalizeCommercialUnit(selected?.unit||"pieza");const box=validBoxFactor(selected?.boxFactor);const factor=selected?presentationFactor(selected,presentation)??1:1;const baseQuantity=Math.max(0,Math.floor(Number(quantity)||0))*factor;
  function close(){if(!busy)setOpen(false)}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!data)return;const form=new FormData(event.currentTarget);setBusy(true);setError("");try{const response=await fetch("/api/commercial-movement",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,productId:Number(productId),presentation,quantity:Number(quantity),clientId:form.get("clientId"),reference:form.get("reference"),notes:form.get("notes")})});const json=await response.json() as {error?:string;message?:string};if(!response.ok)throw new Error(json.error||"No se pudo registrar el movimiento.");window.alert(json.message||"Movimiento registrado.");window.location.reload()}catch(value){setError(value instanceof Error?value.message:"No se pudo registrar el movimiento.")}finally{setBusy(false)}}
  if(!open||!data)return error&&!open?<div className="update-banner"><span><strong>No se pudo abrir el movimiento</strong><small>{error}</small></span><button onClick={()=>setError("")}>Cerrar</button></div>:null;
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div className="modal"><div className="modal-head"><div><p>MOVIMIENTO DE INVENTARIO</p><h2>Registrar movimiento</h2></div><button onClick={close} disabled={busy}>×</button></div><form onSubmit={submit}>{error&&<div className="alert error">{error}</div>}<div className="form-grid"><label><span>Tipo *</span><select value={type} onChange={event=>setType(event.target.value)} required>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label><span>Producto *</span><select value={productId} onChange={event=>{const value=event.target.value;setProductId(value);const product=data.products.find(row=>String(row.id)===value);setPresentation(normalizeCommercialUnit(product?.unit||"pieza"))}} required>{data.products.map(product=><option key={product.id} value={product.id}>{product.sku} · {product.name} · {product.currentStock} {unitLabel(product.unit,product.currentStock!==1)}</option>)}</select></label><label><span>Forma *</span><select value={presentation} onChange={event=>setPresentation(event.target.value)}><option value={baseUnit}>{unitLabel(baseUnit).charAt(0).toUpperCase()+unitLabel(baseUnit).slice(1)}</option>{box?<option value="caja">Caja · {box} {unitLabel(baseUnit,box!==1)}</option>:null}</select></label><label><span>Cantidad *</span><input type="number" min="1" step="1" inputMode="numeric" value={quantity} onChange={event=>setQuantity(event.target.value)} required/></label><label><span>Cliente relacionado</span><select name="clientId"><option value="">Sin seleccionar</option>{data.clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label><span>Folio o referencia</span><input name="reference"/></label><label className="wide"><span>Observaciones</span><input name="notes"/></label><div className="field-note wide">Este movimiento cambiará el inventario en <b>{baseQuantity} {unitLabel(baseUnit,baseQuantity!==1)}</b>. El contenido interno de un juego no se multiplica.</div></div><div className="modal-actions"><button type="button" className="ghost" onClick={close} disabled={busy}>Cancelar</button><button className="primary" disabled={busy||!type}>{busy?"Guardando…":"Guardar movimiento"}</button></div></form></div></div>;
}
